### ISSUE TITLE
Memory Error for Large Dataset - Unable to allocate 52.7 GiB

### ISSUE THREAD

**Issue by jerempir** [ViKarp/TimeSeriesSurfers#1]
When processing a dataset spanning more than 6 months, the program crashes with a memory allocation error at the step "Training end evaluating model."

An error like this:
"Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\TimeSeriesSurfers-main\src\scripts\run_pipeline.py", line 24, in <module>
    pipeline = ClassicPipeline(BaseDataStreamer, Last10ValuesCoaches, BaseLogger, data_path, target,
  File "C:\Users\user\PycharmProjects\TimeSeriesSurfers-main\src\Pipelines\base.py", line 29, in __init__
    self.coach = coach(data_processor=data_processor, memory=memory, trigger=trigger, model=model,
  File "C:\Users\user\PycharmProjects\TimeSeriesSurfers-main\src\Coaches\base.py", line 45, in __init__
    self.train(train_data)
  File "C:\Users\user\PycharmProjects\TimeSeriesSurfers-main\src\Coaches\base.py", line 63, in train
    self.model.train(np.arange(len(train_data_scaled)).reshape(-1, 1), train_data_scaled)
  File "C:\Users\user\PycharmProjects\TimeSeriesSurfers-main\src\Models\base.py", line 190, in train
    self.model.fit(X_train, y_train.values)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\_gpr.py", line 307, in fit
    self._constrained_optimization(
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\_gpr.py", line 652, in _constrained_optimization
    opt_res = scipy.optimize.minimize(
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\scipy\optimize\_minimize.py", line 696, in minimize
    res = _minimize_lbfgsb(fun, x0, args, jac, bounds,
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\scipy\optimize\_lbfgsb_py.py", line 305, in _minimize_lbfgsb
    sf = _prepare_scalar_function(fun, x0, jac=jac, args=args, epsilon=eps,
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\scipy\optimize\_optimize.py", line 332, in _prepare_scalar_function
    sf = ScalarFunction(fun, x0, args, grad, hess,
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\scipy\optimize\_differentiable_functions.py", line 158, in __init__
    self._update_fun()
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\scipy\optimize\_differentiable_functions.py", line 251, in _update_fun
    self._update_fun_impl()
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\scipy\optimize\_differentiable_functions.py", line 155, in update_fun
    self.f = fun_wrapped(self.x)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\scipy\optimize\_differentiable_functions.py", line 137, in fun_wrapped
    fx = fun(np.copy(x), *args)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\scipy\optimize\_optimize.py", line 76, in __call__
    self._compute_if_needed(x, *args)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\scipy\optimize\_optimize.py", line 70, in _compute_if_needed
    fg = self.fun(x, *args)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\_gpr.py", line 297, in obj_func
    lml, grad = self.log_marginal_likelihood(
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\_gpr.py", line 576, in log_marginal_likelihood
    K, K_gradient = kernel(self.X_train_, eval_gradient=True)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py", line 963, in __call__
    K2, K2_gradient = self.k2(X, Y, eval_gradient=True)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\gaussian_process\kernels.py", line 1574, in __call__
    K_gradient = (K * squareform(dists))[:, :, np.newaxis]
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 9.63 GiB for an array with shape (35948, 35948) and data type float64"

![2024-10-21_19-19-45](https://github.com/user-attachments/assets/0fcd4612-d53b-4c87-8793-ee38ec40f3b6)

**Comment by ViKarp** [comment]
Too much memory is required to train Gaussian processes. It is necessary to create a parameter with maximum size of training data.
